vendery/admin_panel/urls.py
from django.urls import path
from .views import *
app_name = 'panel'

urlpatterns = [
    path('', ViewAdminPanel.as_view(), name='view-admin-panel'),
    path('login', LoginPanel.as_view(), name='view-login-panel'),
    path('logout', LogoutPanel.as_view(), name='view-logout-panel'),
    path('categoria/', ViewCreateCategory.as_view(), name='view-create-category'),
    path('categorias/', ViewListCategory.as_view(), name='view-list-category'),
    path('categoria/<int:pk>/', ViewUpdateCategory.as_view(), name='view-update-category'),
    path('categoria/<int:pk>/eliminar/', ViewDeleteCategory.as_view(), name='view-delete-category'),
    path('clientes/', ViewListClient.as_view(), name='view-list-client'),
    path('nuevo-cliente/', ViewCreateClient.as_view(), name='view-create-client'),
    path('cliente/<int:pk>/', ViewUpdateClient.as_view(), name='view-update-client'),
    path('cliente/<int:pk>/eliminar/', ViewDeleteClient.as_view(), name='view-delete-client'),
    path('productos/', ViewListProducts.as_view(), name='view-list-product'),
    path('nuevo-producto/', ViewCreateProducts.as_view(), name='view-create-product'),
    path('producto/<int:pk>/', ViewUpdateProducts.as_view(), name='view-update-product'),
    path('producto/<int:pk>/eliminar/', ViewDeleteProducts.as_view(), name='view-delete-product'),
    path('provedores/', ViewListProvider.as_view(), name='view-list-provider'),
    path('nuevo-proveedor/', ViewCreateProvider.as_view(), name='view-create-provider'),
    path('proveedor/<int:pk>/', ViewUpdateProvider.as_view(), name='view-update-provider'),
    path('proveedor/<int:pk>/eliminar/', ViewDeleteProvider.as_view(), name='view-delete-provider'),
    path('vendedores/', ViewListVendors.as_view(), name='view-list-vendors'),
    path('nuevo-vendedor/', ViewCreateVendors.as_view(), name='view-create-vendor'),
    path('vendedor/<int:pk>/', ViewUpdateVendors.as_view(), name='view-update-vendors'),
    path('vendedor/<int:pk>/eliminar/', ViewDeleteVendor.as_view(), name='view-delete-vendors'),
    path('gastos/', ViewListExpenses.as_view(), name='view-list-expenses'),
    path('nuevo-gasto/', ViewCreateExpenses.as_view(), name='view-create-expenses'),
    path('gasto/<int:pk>/', ViewUpdateExpenses.as_view(), name='view-update-expenses'),
    path('gasto/<int:pk>/eliminar/', ViewDeleteExpense.as_view(), name='view-delete-expenses'),
    path('talla/', ViewCreateProductSize.as_view(), name='view-create-product-size'),
    path('tallas/', ViewListProductSize.as_view(), name='view-list-product-size'),
    path('sells/', ViewSells.as_view(), name='view-sells'),
]

vendery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('', RedirectView.as_view(url='inventory/')),
    path('admin/', admin.site.urls),
    path('inventory/', include('vendery.inventory.urls')),
    path('panel/', include('vendery.admin_panel.urls')),
    path('catalogo/', include('vendery.landing_page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendery/tenants/huellitas/templates/templates/admin_panel/views/sizes/list_product_size.html
{% extends "admin_panel/layout/base_admin.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Tallas de productos registrados
            </h1>
        </div>
    </div>
    <div class="text-right">
    <a type="button" class="btn btn-success" href="{% url 'panel:view-create-product-size' %}">Nuevo</a>
    </div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Talla</th>
        </tr>
        </thead>
        <tbody>
        {% for size in sizes %}
            <tr>
                <th scope="row">{{ size.id }}</th>
                <td>{{ size.size}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

vendery/tenants/huellitas/templates/templates/admin_panel/views/sizes/new_product_size.html
{% extends "admin_panel/layout/base_admin.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <h1 class="page-header">Registrar Talla</h1>
    <div class="text-right">
       {% include 'admin_panel/components/breadcrumb.html'%}
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="inputSize">Talla</label>
            {% render_field form.size class="form-control" %}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-info">Registrar</button>
        </div>
    </form>
{% endblock %}