vendery/inventory/urls.py
from django.urls import path
from .views import *
from django.conf.urls import handler404, handler500
app_name = 'inventory'

urlpatterns = [
    path('', ViewInventory.as_view(), name='view-inventory'),
    path('login', Login.as_view(), name='view-login'),
    path('logout', Logout.as_view(), name='view-logout'),
    path('mis-ventas/', ViewSales.as_view(), name='view-sales'),
    path('venta/', ViewSalesData.as_view(), name='view-sales-data'),
    path('nota-remision/', ViewNote.as_view(), name='view-note'),
    # path('nota-remision-datos/<uuid:token>/', ViewTemporaryOrders.as_view(), name='view-note-data'),
    path('inventario/', ViewInventoryAll.as_view(), name='view-inventory-all'),
    path('clientes/', ViewCustomers.as_view(), name='view-customers'),
    path('nuevo-cliente/', ViewCreateCustomers.as_view(), name='view-customers-new'),
    path('actualizar-cliente/<int:pk>/', ViewUpdateCustomers.as_view(), name='view-customers-update'),
    path('search-products', SearchView.as_view(), name='search_products'),
    path('producto/<int:pk>/', ViewShowProduct.as_view(), name='view-product-show'),
    path('gastos/', ViewListExpenses.as_view(), name='view-list-expenses'),
    path('nuevo-gasto/', ViewCreateExpenses.as_view(), name='view-create-expenses'),
    path('gasto/<int:pk>', ViewUpdateExpenses.as_view(), name='view-update-expenses'),
    path('send-note/', ViewSendNote.as_view(), name='view-send-note'),
]
handler404 = Error404.as_view()
# handler500 = Error500.as_error_view()

vendery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('', RedirectView.as_view(url='inventory/')),
    path('admin/', admin.site.urls),
    path('inventory/', include('vendery.inventory.urls')),
    path('panel/', include('vendery.admin_panel.urls')),
    path('catalogo/', include('vendery.landing_page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendery/tenants/huellitas/templates/templates/components/base_login.html
<head>
    <title>Vendery</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="icon" href="" size="400x400" type="image/png">
    <!-- jQuery JS -->
    <script
            src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <style>
        body {
            background: #151818;
        }

        .card-signin {
            border: 0;
            border-radius: 1rem;
            box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
        }

        .card-signin .card-title {
            margin-bottom: 2rem;
            font-weight: 300;
            font-size: 1.5rem;
        }

        .card-signin .card-body {
            padding: 2rem;
        }

        .form-signin {
            width: 100%;
        }

        .form-signin .btn {
            font-size: 100%;
            border-radius: 5rem;
            letter-spacing: .1rem;
            font-weight: bold;
            padding: 1rem;
            transition: all 0.2s;
        }

        .form-label-group {
            position: relative;
            margin-bottom: 1rem;
        }

        .form-label-group input {
            height: auto;
            border-radius: 2rem;
        }

        .form-label-group > input,
        .form-label-group > label {
            padding: var(--input-padding-y) var(--input-padding-x);
        }

        .btn-contra {
            color: white;
            background-color: #3b8d98;
        }

        /* Fallback for Edge
        -------------------------------------------------- */

        @supports (-ms-ime-align: auto) {
            .form-label-group > label {
                display: none;
            }

            .form-label-group input::-ms-input-placeholder {
                color: #777;
            }
        }

        /* Fallback for IE
        -------------------------------------------------- */

        @media all and (-ms-high-contrast: none),
        (-ms-high-contrast: active) {
            .form-label-group > label {
                display: none;
            }

            .form-label-group input:-ms-input-placeholder {
                color: #777;
            }
        }
    </style>

</head>

vendery/tenants/huellitas/templates/templates/components/card_product.html
{% load static %}

<style>
@media (min-width:300px)  {
/* smartphones */
.img-size {
width: 150px;
height: 150px;
}
}

@media (min-width:1025px) {
/*laptops, and desktops*/
.img-size {
width: 250px;
height: 250px;
}
}


</style>
<link href="{% static 'css/utils.css' %}" rel="stylesheet">
<div class="container pt-5">
    <div class="row">
        {% for vendor in vendors %}
            {% for product in vendor.products.all %}
                <div class='col-6 col-sm-4 col-md-3 p-1'>
                    <div class="card mb-2" style="border-radius: 0.5rem;">
                        <img class="card-img-top p-2 img-size"  src="{{ product.image.url }}" alt="Card image cap">
                            {% include 'components/card_product_body.html' %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
    </div>

</div>
<style>
    .div-total {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #343A40;
        padding: 0;
        text-align: center;

    }

</style>
<hr class="pt-5 border-0">
<div class="div-total">
            <div class="d-flex justify-content-between">
                <button type="button" class="btn btn-info" id="product-cart">
                    Ver Carrito
                </button>
                    <div class="p-2 bg-light text-dark" id="total-amount" style="border-radius: 0.5rem; width:10rem;">Total: $0.00
                </div>
                <button type="button"
                        class="btn btn-success"
{#                        data-toggle="modal"#}
{#                        data-target="#exampleModal"#}
{#                        href="{% url 'inventory:view-inventory'%}"#}
                        id="sell-button">
                    Vender
                </button>
            </div>
    <hr class="border-0">
</div>

{% include 'components/cart_modal.html' %}
        
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Venta</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Esta seguro de realizar la venta!?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
              <a type="button" class="btn btn-dark" id="sell-button" >
                  Confirmar
              </a>
      </div>
    </div>
  </div>
</div>

vendery/tenants/huellitas/templates/templates/components/card_product_body.html
{% load static %}
<div class="card-body-product">
    <div>
        <p class='product-name'>{{ product.name }}</p>
        {# Idk why but closing the last tag it breakes the products aligment#}
        <h5 class='card-title'>Precio: ${{ product.price }} MXN</h5
    </div>
    <div>
        <select class="form-select product-size" aria-label="Default select example">
            <option selected>Selecciona Talla</option>
            {% for size in product.size.all %}
                <option value="{{ size }}">{{ size }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group" style="padding-top: 1rem">
        <small id="emailHelp" class="form-text text-muted">Ingrese cantidades a vender</small>
        <input type="number" min="0" class="form-control product-quantity" aria-describedby="emailHelp"
               placeholder="0 Unidades">
    </div>
    <div>
        <button type="button" class="btn btn-primary button-add"
                data-price="{{ product.price }}"
                data-productid="{{ product.id }}"
                data-productname="{{ product.name }}">Agregar</button>
    </div>
</div>

vendery/tenants/huellitas/templates/templates/components/cart_modal.html
<style type="text/css">
    .tg {
        border-collapse: collapse;
        border-spacing: 0;
    }

    .tg td {
        border-color: black;
        border-style: solid;
        border-width: 1px;
        font-family: Arial, sans-serif;
        font-size: 14px;
        overflow: hidden;
        padding: 10px 5px;
        word-break: normal;
    }

    .tg th {
        border-color: black;
        border-style: solid;
        border-width: 1px;
        font-family: Arial, sans-serif;
        font-size: 14px;
        font-weight: normal;
        overflow: hidden;
        padding: 10px 5px;
        word-break: normal;
    }

    .tg .tg-0pky {
        border-color: inherit;
        text-align: left;
        vertical-align: top
    }

    .tg .tg-0lax {
        text-align: left;
        vertical-align: top
    }
</style>
<div class="modal fade" id="cart-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Productos Agregados</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div>
                <table class="tg" id="cart-modal-table">
                    <thead>
                    <tr>
                        <th class="tg-0pky">ID</th>
                        <th class="tg-0pky">Producto</th>
                        <th class="tg-0pky">Precio</th>
                        <th class="tg-0pky">Talla</th>
                        <th class="tg-0pky">Cantidad</th>
                        <th class="tg-0lax">Subtotal</th>
                        <th class="tg-0lax">Acción</th>
                    </tr>
                    </thead>
                    <tbody class="cart-modal-table-body">
                    {# Data comming from inventory.js#}
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-info" id="continue-button">Continuar</button>
            </div>
        </div>
    </div>
</div>

vendery/tenants/huellitas/templates/templates/components/clients.html
<div class="form-group">
    <label for="exampleFormControlSelect1"></label>
    <select class="form-control" name="client" id="select-client" required>
        <option>Cliente a vender</option>
        {% for client in clients %}
            <option value="{{ client.id }}" id="{{ client.id }}">{{ client.name }}</option>
        {% endfor %}
    </select>
</div>

vendery/tenants/huellitas/templates/templates/components/nav.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a href="{% url 'inventory:view-inventory' %}">
       <img src="{% static 'img/logo.png' %}" style="height: 3rem; width: 3rem;" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'inventory:view-inventory' %}">Inicio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:view-sales' %}">Ventas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:view-inventory-all' %}">Inventario</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:view-customers' %}">Clientes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:view-list-expenses' %}">Gastos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-person-fill text-info" viewBox="0 0 16 16">
                        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    </svg>
                    {{ user.get_username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Datos</a>
                    <a class="dropdown-item" href="{% url 'inventory:view-logout' %}">Cerrar sesion</a>
                </div>
            </li>
        </ul>

    </div>
</nav>

vendery/tenants/huellitas/templates/templates/components/search.html
<form class="form-inline " action="{% url 'inventory:search_products' %}" method="get">
    <input class="form-control" style=" width:100%; border-radius: 3rem;" type="text" name="q" placeholder="Buscar producto..." aria-label="Buscar">
    {#        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>#}
</form>

vendery/tenants/huellitas/templates/templates/components/table.html
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">Producto</th>
    <th class="tg-0pky">Precio</th>
    <th class="tg-0pky">Talla</th>
    <th class="tg-0pky">Cantidad</th>
    <th class="tg-0lax">Subtotal</th>
    <th class="tg-0lax">Eliminar</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">Zapato de nina</td>
    <td class="tg-0pky">4</td>
    <td class="tg-0pky">$100</td>
    <td class="tg-0pky">$400</td>
    <td class="tg-0lax">$200</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Zapato de nina</td>
    <td class="tg-0pky">1</td>
    <td class="tg-0pky">$200</td>
    <td class="tg-0pky">$200</td>
    <td class="tg-0lax">$200</td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Zapato de nina</td>
    <td class="tg-0pky">3</td>
    <td class="tg-0pky">$50</td>
    <td class="tg-0pky">$150</td>
    <td class="tg-0lax">$200</td>
    <td class="tg-0lax"></td>
  </tr>
</tbody>
</table>