vendery/admin_panel/urls.py
from django.urls import path
from .views import *
app_name = 'panel'

urlpatterns = [
    path('', ViewAdminPanel.as_view(), name='view-admin-panel'),
    path('login', LoginPanel.as_view(), name='view-login-panel'),
    path('logout', LogoutPanel.as_view(), name='view-logout-panel'),
    path('categoria/', ViewCreateCategory.as_view(), name='view-create-category'),
    path('categorias/', ViewListCategory.as_view(), name='view-list-category'),
    path('categoria/<int:pk>/', ViewUpdateCategory.as_view(), name='view-update-category'),
    path('categoria/<int:pk>/eliminar/', ViewDeleteCategory.as_view(), name='view-delete-category'),
    path('clientes/', ViewListClient.as_view(), name='view-list-client'),
    path('nuevo-cliente/', ViewCreateClient.as_view(), name='view-create-client'),
    path('cliente/<int:pk>/', ViewUpdateClient.as_view(), name='view-update-client'),
    path('cliente/<int:pk>/eliminar/', ViewDeleteClient.as_view(), name='view-delete-client'),
    path('productos/', ViewListProducts.as_view(), name='view-list-product'),
    path('nuevo-producto/', ViewCreateProducts.as_view(), name='view-create-product'),
    path('producto/<int:pk>/', ViewUpdateProducts.as_view(), name='view-update-product'),
    path('producto/<int:pk>/eliminar/', ViewDeleteProducts.as_view(), name='view-delete-product'),
    path('provedores/', ViewListProvider.as_view(), name='view-list-provider'),
    path('nuevo-proveedor/', ViewCreateProvider.as_view(), name='view-create-provider'),
    path('proveedor/<int:pk>/', ViewUpdateProvider.as_view(), name='view-update-provider'),
    path('proveedor/<int:pk>/eliminar/', ViewDeleteProvider.as_view(), name='view-delete-provider'),
    path('vendedores/', ViewListVendors.as_view(), name='view-list-vendors'),
    path('nuevo-vendedor/', ViewCreateVendors.as_view(), name='view-create-vendor'),
    path('vendedor/<int:pk>/', ViewUpdateVendors.as_view(), name='view-update-vendors'),
    path('vendedor/<int:pk>/eliminar/', ViewDeleteVendor.as_view(), name='view-delete-vendors'),
    path('gastos/', ViewListExpenses.as_view(), name='view-list-expenses'),
    path('nuevo-gasto/', ViewCreateExpenses.as_view(), name='view-create-expenses'),
    path('gasto/<int:pk>/', ViewUpdateExpenses.as_view(), name='view-update-expenses'),
    path('gasto/<int:pk>/eliminar/', ViewDeleteExpense.as_view(), name='view-delete-expenses'),
    path('talla/', ViewCreateProductSize.as_view(), name='view-create-product-size'),
    path('tallas/', ViewListProductSize.as_view(), name='view-list-product-size'),
    path('sells/', ViewSells.as_view(), name='view-sells'),
]

vendery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('', RedirectView.as_view(url='inventory/')),
    path('admin/', admin.site.urls),
    path('inventory/', include('vendery.inventory.urls')),
    path('panel/', include('vendery.admin_panel.urls')),
    path('catalogo/', include('vendery.landing_page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendery/tenants/huellitas/templates/templates/admin_panel/views/products/delete_products.html
{% load static %}

<div class="modal-dialog modal-sm" role="document" >
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <h5 class="modal-title" id="exampleModalLabel">Esta seguro de eliminar el Producto :
                    <br><b>{{ product.name }} </b></h5>
                <hr>
                <form method="post" action="{% url 'panel:view-delete-product' pk %}">
                    {% csrf_token %}
                    <div class="d-flex justify-content-center">
                        <a type="button" class="btn btn-success" data-dismiss="modal">Cancelar</a>
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

vendery/tenants/huellitas/templates/templates/admin_panel/views/products/list_product.html
{% extends "admin_panel/layout/base_admin.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <style>



    @media (min-width:300px)  {
/* smartphones */
    .img-p{
        height: 5rem; width: 5rem;
    }
}

@media (min-width:1025px) {
/*laptops, and desktops*/
    .img-p{
        height: 10rem; width: 10rem;
    }
}
    </style>
        <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Productos
            </h1>
        </div>
    </div>
    <div class="text-right">
        <a type="button" class="btn btn-success" href="{% url 'panel:view-create-product' %}">Nuevo</a>
    </div>
    <div class="table-responsive">
    <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Imagen</th>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      <th scope="col">Eliminar</th>
    </tr>
  </thead>
  <tbody>
  {% for product in products %}
    <tr>
      <th scope="row"><img class="img-p" src="{{ product.image.url }}"></th>
      <td><a href="{% url 'panel:view-update-product' product.id %}">{{ product.name }}</a></td>
      <td>{{ product.price }}</td>
      <td><a type="button" class="btn btn-danger"  onclick="modal_delete('{% url 'panel:view-delete-product' product.id %}')"><i class="fa fa-trash" aria-hidden="true"></i>
</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>

<div class="modal fade" id="delete_product" role="dialog"></div>
<script>
    function modal_delete(url) {
        $('#delete_product').load(url, function () {
            $(this).modal('show');
        });
    }
    </script>
{% endblock %}

vendery/tenants/huellitas/templates/templates/admin_panel/views/products/new_product.html
{% extends "admin_panel/layout/base_admin.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Productos
            </h1>
        </div>
    </div>
    <div class="text-right">
       {% include 'admin_panel/components/breadcrumb.html'%}
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputName">Nombre</label>
                {% render_field form.name class="form-control" %}
            </div>
            <div class="form-group col-md-6">
                <label for="inputPhone">Precio</label>
                {% render_field form.price class="form-control" %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputName">Estatus</label>
                {% render_field form.status class="form-control" %}
            </div>
            <div class="form-group col-md-6">
                <label for="inputPhone">Categoria</label>
                {% render_field form.category class="form-control" %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="inputName">Existencia</label>
                {% render_field form.stock class="form-control" %}
            </div>

            <div class="form-group col-md-4">
                <label for="inputName">Imagen</label>
                {% render_field form.image class="form-control" %}
            </div>
            <div class="form-group col-md-4">
                <label for="inputSizes">Tallas</label>
                {% render_field form.size class="form-check-input" %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="inputPhone">Descripcion</label>
                {% render_field form.description class="form-control" %}
            </div>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-info">Registrar</button>
        </div>
    </form>
{% endblock %}

vendery/tenants/huellitas/templates/templates/admin_panel/views/products/update_product.html
{% extends "admin_panel/layout/base_admin.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
              Actualizar Productos
            </h1>
        </div>
    </div>
    <div class="text-right">
       {% include 'admin_panel/components/breadcrumb.html'%}
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputName">Nombre</label>
                {% render_field form.name class="form-control" %}
            </div>
            <div class="form-group col-md-6">
                <label for="inputPhone">Precio</label>
                {% render_field form.price class="form-control" %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputName">Estatus</label>
                {% render_field form.status class="form-control" %}
            </div>
            <div class="form-group col-md-6">
                <label for="inputPhone">Categoria</label>
                {% render_field form.category class="form-control" %}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputName">Existencia</label>
                {% render_field form.stock class="form-control" %}
            </div>

            <div class="form-group col-md-6">
                <label for="inputSizes">Tallas</label>
                {% render_field form.size class="form-check-input" %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputName">Imagen</label>
                <img style="height: 10rem; width: 10rem;" src="{{ form.instance.image.url }}">
                {% render_field form.image class="form-control" %}
            </div>
            <div class="form-group col-md-6">
                <label for="inputPhone">Descripcion</label>
                {% render_field form.description class="form-control" %}
            </div>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-info">Actualizar</button>
        </div>
    </form>
{% endblock %}