vendery/inventory/urls.py
from django.urls import path
from .views import *
from django.conf.urls import handler404, handler500
app_name = 'inventory'

urlpatterns = [
    path('', ViewInventory.as_view(), name='view-inventory'),
    path('login', Login.as_view(), name='view-login'),
    path('logout', Logout.as_view(), name='view-logout'),
    path('mis-ventas/', ViewSales.as_view(), name='view-sales'),
    path('venta/', ViewSalesData.as_view(), name='view-sales-data'),
    path('nota-remision/', ViewNote.as_view(), name='view-note'),
    # path('nota-remision-datos/<uuid:token>/', ViewTemporaryOrders.as_view(), name='view-note-data'),
    path('inventario/', ViewInventoryAll.as_view(), name='view-inventory-all'),
    path('clientes/', ViewCustomers.as_view(), name='view-customers'),
    path('nuevo-cliente/', ViewCreateCustomers.as_view(), name='view-customers-new'),
    path('actualizar-cliente/<int:pk>/', ViewUpdateCustomers.as_view(), name='view-customers-update'),
    path('search-products', SearchView.as_view(), name='search_products'),
    path('producto/<int:pk>/', ViewShowProduct.as_view(), name='view-product-show'),
    path('gastos/', ViewListExpenses.as_view(), name='view-list-expenses'),
    path('nuevo-gasto/', ViewCreateExpenses.as_view(), name='view-create-expenses'),
    path('gasto/<int:pk>', ViewUpdateExpenses.as_view(), name='view-update-expenses'),
    path('send-note/', ViewSendNote.as_view(), name='view-send-note'),
]
handler404 = Error404.as_view()
# handler500 = Error500.as_error_view()

vendery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('', RedirectView.as_view(url='inventory/')),
    path('admin/', admin.site.urls),
    path('inventory/', include('vendery.inventory.urls')),
    path('panel/', include('vendery.admin_panel.urls')),
    path('catalogo/', include('vendery.landing_page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendery/tenants/huellitas/templates/templates/views/expenses/list_expenses.html
{% extends "layouts/base.html" %}
{% load static %}
{% block main %}
    <div class="container">

        <div class="card">
            <div class="card-header text-white text-center" style="background-color: #3d90bf">
                Gastos
            </div>
            <div class="card-body">
            <div class="text-right">
              <a type="button" href="{% url 'inventory:view-create-expenses' %}" class="btn btn-info"> Agregar Gasto </a>
            </div>
            <hr>
                {% if expenses %}
                    <table class="table table-bordered table-responsive-sm">
                        <thead>
                        <tr>
                            <th scope="col">Clave</th>
                            <th scope="col">Razón</th>
                            <th scope="col">Monto</th>
                            <th scope="col">Fecha</th>

                        </tr>
                        </thead>

                        <tbody>
                        {% for exp in expenses %}
                            <tr>
                                <th scope="row"><a href="{% url 'inventory:view-update-expenses' exp.id %}"> {{ exp.id }}</a>
                                </th>
                                <td>{{ exp.amount }}</td>
                                <td>{{ exp.reason }}</td>
                                <td>{{ exp.creation_date }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="text-right">
                    Total:
                {% else %}
                    <h4 class="text-center"> No existen gastos</h4>
                {% endif %}
            </div>
        </div>

    </div>
        <div class="modal fade" id="view_ticket" role="dialog"></div>
<script>
    function modal_ticket(url) {
        $('#view_ticket').load(url, function () {
            $(this).modal('show');
        });
    }
    </script>
{% endblock %}

vendery/tenants/huellitas/templates/templates/views/expenses/new_expenses.html
{% extends "layouts/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block main %}
    <div class="container">

        <div class="card">
            <div class="card-header text-white text-center" style="background-color: #3d90bf">
                Nuevo Gasto
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputName">Monto</label>
                            {% render_field form.amount class="form-control" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputPhone">Concepto</label>
                            {% render_field form.reason class="form-control" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="inputEmail">Comentario</label>
                            {% render_field form.comments class="form-control" %}
                        </div>
                    </div>
                    <input type="hidden" name="vendor" id="vendor" value="{{ vendor.id }}">

                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-dark">Registrar</button>
                    </div>

                </form>
            </div>
        </div>

    </div>

{% endblock %}

vendery/tenants/huellitas/templates/templates/views/expenses/update_expenses.html
{% extends "layouts/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block main %}
    <div class="container">

        <div class="card">
            <div class="card-header text-white text-center" style="background-color: #3d90bf">
                Actualizar Gasto
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputName">Monto</label>
                            {% render_field form.amount class="form-control" %}
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputPhone">Concepto</label>
                            {% render_field form.reason class="form-control" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="inputEmail">Comentario</label>
                            {% render_field form.comments class="form-control" %}
                        </div>
                    </div>
                    <input type="hidden" name="vendor" id="vendor" value="{{ vendor.id }}">

                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-dark">Actualizar</button>
                    </div>

                </form>
            </div>
        </div>

    </div>

{% endblock %}